@FinCs = localhost:5196

POST {{FinCs}}/api/expenses
Content-Type: application/json
Accept: application/json

{
  "amount": 100.50,
  "category": "Food",
  "description": "Lunch with colleagues",
  "date": "2024-02-09T12:30:00",
  "title": "titulo"
}
